### ISSUE TITLE
how to run this code "codes_for_moa"

### ISSUE THREAD

**Issue by asmaso** [alipsgh/codes_for_moa#1]
please help me in this point,
I make new java application project in java and put classes but not find main class 
Thanks in advance

**Comment by alipsgh** [comment]
Hey,
These classes are prepared for the [MOA](https://github.com/Waikato/moa) framework. You need to import MOA to your IDE of choice, and then add my DDMs under the **driftdetection** package! Once you run MOA via your IDE, or after creating a jar file, you will see my DDMs are available for use in MOA. I hope my answer helps you out.

**Comment by asmaso** [comment]
Hi,
Thanks for reply
Iam download moa as told me from link https://github.com/Waikato/moa
then open it in my IDE netbeans, then run it it take some time to download some package 
and then give me this error 
![error moa](https://user-images.githubusercontent.com/7336169/53254796-d36ee800-36cc-11e9-9917-833786eaba6d.png)

**Comment by alipsgh** [comment]
You probably need to create a Maven project.
Let me prepare a tutorial in Eclipse, and I will share it in the repository.

**Comment by alipsgh** [comment]
Hi there!
Please refer to [my tutorial](https://github.com/alipsgh/codes_for_moa/blob/master/tutorial.md).
Good luck.
