### ISSUE TITLE
Install MOA in NetBeans 

### ISSUE THREAD

**Issue by asmaso** [alipsgh/codes_for_moa#2]
Hello
 Please help me solve this error when trying to install moa in NetBeans

cd F:\MOA\updated_maven\moa-abae570a6234d2d5113341e3097d84a6eae146b5; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_191" cmd /c "\"\"C:\\Program Files\\NetBeans 8.0.2\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath moa.gui.GUI\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_191\\bin\\java.exe\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.0.2\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 process-classes org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.2.1/exec-maven-plugin-1.2.1.pom

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1.015s
Finished at: Fri Jan 28 15:15:48 EET 2022
Final Memory: 6M/121M
------------------------------------------------------------------------
Plugin org.codehaus.mojo:exec-maven-plugin:1.2.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:exec-maven-plugin:jar:1.2.1: Could not transfer artifact org.codehaus.mojo:exec-maven-plugin:pom:1.2.1 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.2.1/exec-maven-plugin-1.2.1.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by alipsgh** [comment]
@asmaso Please ask the MOA creators to have a look into this, and report the issue here:
https://github.com/Waikato/moa/issues
